### ISSUE TITLE
Error during startup - StatusLogger No log4j2 configuration file found

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/wso2-test-grid#92]
**Description:**
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vidurananayakkara** [comment]
Resolved by adding file https://github.com/wso2-incubator/wso2-test-grid/blob/master/core/src/main/resources/log4j2.xml
